version: '3.8'

services:
  devsentry:
    build: .
    container_name: devsentry
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always